server:
  port: 8080
spring:
  application:
    name: hb_zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

#路由表
zuul:
  routes:
    hb_admin: /admin/**
    hb_web: /web/**


