#配置服务器端口号
server:
  port: 8083
#服务名
spring:
  application:
    name: hb_web
  datasource: #数据库连接信息
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///hbuy?useSSL=false
    username: root
    password: root
    hikari:
          maximum-pool-size: 30
          minimum-idle: 10
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /pages/
      suffix:

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
  devtools:
    restart:
      exclude: static/**,pages/**,templates/**

#整合xml形式的mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
